name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup npm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install
